@echo off
REM Create the virtual environment and install dependencies.
REM
REM Prefers Python 3.12, then 3.11: madmom - which supplies downbeat tracking
REM and one of the three chord engines - cannot be built on 3.13 or newer.
REM The app runs without madmom, in a reduced mode. See README.md.
setlocal
cd /d "%~dp0"

set PY=
for %%V in (3.12 3.11 3.13) do (
    if not defined PY (
        py -%%V --version >nul 2>&1 && set PY=py -%%V
    )
)
if not defined PY (
    echo Could not find Python 3.11, 3.12 or 3.13 via the py launcher.
    echo Falling back to whatever "python" resolves to.
    set PY=python
)

echo Creating virtual environment with: %PY%
%PY% -m venv .venv
if errorlevel 1 (
    echo Failed to create the virtual environment.
    pause
    exit /b 1
)

call .venv\Scripts\activate.bat
python -m pip install --upgrade pip

echo.
echo === Installing dependencies ===
python -m pip install -r requirements.txt
if errorlevel 1 (
    echo Dependency installation failed.
    pause
    exit /b 1
)

echo.
echo === Installing madmom (optional, needs a C compiler) ===
REM Three things make madmom awkward to install, all handled here:
REM  1. Its setup.py imports Cython without declaring it, so pip's isolated
REM     build environment cannot see it - hence --no-build-isolation, which
REM     in turn needs setuptools and wheel present in the venv.
REM  2. The PyPI sdist ships C files generated by an old Cython that include
REM     longintrepr.h, a header Python 3.12 removed. Installing from git means
REM     there are no stale C files and Cython regenerates them.
REM  3. It needs NumPy 1.x at build time.
python -c "import sys; sys.exit(0 if sys.version_info < (3, 13) else 1)"
if errorlevel 1 (
    echo Skipping madmom: it cannot be built on Python 3.13 or newer.
    goto :done
)

python -m pip install setuptools wheel "cython>=3.0" "numpy<2"
python -m pip install --no-build-isolation "git+https://github.com/CPJKU/madmom.git"
if errorlevel 1 (
    echo.
    echo madmom could not be installed. This usually means the Microsoft C++
    echo Build Tools are missing. Install them with:
    echo   winget install Microsoft.VisualStudio.2022.BuildTools ^
--override "--quiet --wait --add Microsoft.VisualStudio.Workload.VCTools"
    echo.
    echo VidiChord will still run: bar lines will be estimated rather than
    echo tracked, and chords fused from two engines instead of three.
)

:done
echo.
python -c "import madmom; print('madmom', madmom.__version__, 'is available')" 2>nul
if errorlevel 1 echo Running without madmom ^(reduced mode^).

echo.
echo Setup complete. Run start_backend.bat to launch VidiChord.
pause
